{{- if .Values.imageVectorOverwrite }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gardener-extension.extensionName" . }}-imagevector-overwrite
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gardener-extension.extensionLabels" . | nindent 4 }}
data:
  images_overwrite.yaml: |
{{ .Values.imageVectorOverwrite | indent 4 }}
{{- end }}