apiVersion: {{ include "priorityclassversion" . }}
kind: PriorityClass
metadata:
  name: {{ .Chart.Name }}
value: 1000000000
globalDefault: false
description: "Priority class for the Gardener extension."