apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ template "gardener-extension.extensionName" . }}
  labels:
    {{- include "gardener-extension.extensionLabels" . | nindent 4 }}
value: 1000000000
globalDefault: false
description: "Priority class for the Gardener extension."