---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
{{- if ne .Values.gardener.version "" }}
{{- if semverCompare ">= 1.37-0" .Values.gardener.version }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
