apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "gardener-extension.extensionName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gardener-extension.extensionLabels" . | nindent 4 }}
{{- if ne .Values.gardener.version "" }}
{{- if semverCompare ">= 1.37-0" .Values.gardener.version }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
