apiVersion: extensions.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: acl
  namespace: shoot
spec:
  type: acl
  providerConfig:
    rule:
      action: ALLOW
      type: remote_ip
      cidrs:
        - 0.0.0.0/0
