---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: acl
type: helm
providerConfig:
  # ENCODED_CHART="$(tar -zcf - chart | base64 -w0)" envsubst < example/deployment.yaml > test.yaml
  chart: $ENCODED_CHART
  values:
    image:
      tag: $TAG
    webhook:
      image:
        tag: $TAG
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: acl
spec:
  deployment:
    deploymentRefs:
      - name: acl
  resources:
    - kind: Extension
      type: acl

