---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: acl
type: helm
providerConfig:
  chart: $ENCODED_CHART
  values:
    image:
      repository: ghcr.io/stackitcloud/gardener-extension-acl-controller
      tag: $TAG
    webhook:
      image:
        repository: ghcr.io/stackitcloud/gardener-extension-acl-webhook
        tag: $TAG
    additionalAllowedCidrs: []
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: acl
spec:
  deployment:
    deploymentRefs:
      - name: acl
  resources:
    - kind: Extension
      type: acl

