apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: acl
spec:
  resources:
  - kind: Extension
    primary: true
    reconcileTimeout: 3m0s
    type: acl
    clusterCompatibility:
    - garden
    - shoot
  deployment:
    extension:
      helm:
        ociRepository:
          ref: charts/acl
      # these values will be added to the extension controller deployed for the garden extension
      runtimeClusterValues:
        additionalAllowedCidrs:
          - 0.0.0.0/0
      # these values will be added to the extension controller deployed in the seed for shoot/seed extension
      values:
        additionalAllowedCidrs:
          - 0.0.0.0/0
    admission:
      runtimeCluster:
        helm:
          ociRepository:
            ref: charts/acl-admission-runtime
      virtualCluster:
        helm:
          ociRepository:
            ref: charts/acl-admission-application
