---
apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: extension
build:
  artifacts:
  - image: acl
    ko:
      main: ./cmd/gardener-extension-acl/
  - image: acl-admission
    ko:
      main: ./cmd/gardener-extension-admission-acl/
  - image: charts/acl
    custom:
      buildCommand: |
        bash ${GARDENER_DEV_DIR}/push-helm.sh ./charts/gardener-extension-acl/ .image
    requires:
    - image: acl
      alias: IMG
  - image: charts/acl-admission-runtime
    custom:
      buildCommand: |
        bash ${GARDENER_DEV_DIR}/push-helm.sh ./charts/gardener-extension-admission-acl/charts/runtime/ .image
    requires:
    - image: acl-admission
      alias: IMG
  - image: charts/acl-admission-application
    custom:
      buildCommand: |
        bash ${GARDENER_DEV_DIR}/push-helm.sh ./charts/gardener-extension-admission-acl/charts/application/
manifests:
  kustomize:
    paths:
      - ./deploy/extension/local
deploy:
  kubectl: {}
  helm:
    releases:
      - name: gardener-extension-admission-acl
        chartPath: ./charts/gardener-extension-admission-acl
