{{- if .Values.gardener.runtimeCluster.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "name" . }}:garden
  labels:
{{ include "labels" . | indent 4 }}
rules:
- apiGroups:
  - operator.gardener.cloud
  resources:
  - gardens
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "name" . }}:garden
  labels:
{{ include "labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "name" . }}:garden
subjects:
- kind: ServiceAccount
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
