apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    serviceaccount.resources.gardener.cloud/name: extension-acl
    serviceaccount.resources.gardener.cloud/inject-ca-bundle: "true"
    serviceaccount.resources.gardener.cloud/labels: '{"extension": "acl"}'
  labels:
    resources.gardener.cloud/class: garden
    resources.gardener.cloud/purpose: token-requestor
  name: garden-kubeconfig
  namespace: {{ .Release.Namespace }}
stringData:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        server: https://virtual-garden-kube-apiserver.garden.svc.cluster.local
      name: default
    contexts:
    - context:
        cluster: default
        user: token
      name: default
    current-context: default
    kind: Config
    users:
    - name: token
      user: {}
