---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    networking.resources.gardener.cloud/from-world-to-ports: '[{"protocol":"TCP","port":{{ .Values.webhookConfig.serverPort }}}]'
    networking.resources.gardener.cloud/from-all-webhook-targets-allowed-ports: '[{"protocol":"TCP","port":{{ .Values.webhookConfig.serverPort }}}]'
    networking.resources.gardener.cloud/pod-label-selector-namespace-alias: extensions
  labels:
{{ include "labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
{{ include "labels" . | indent 4 }}
  ports:
  - port: {{ .Values.webhookConfig.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.webhookConfig.serverPort }}
