apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    networking.resources.gardener.cloud/from-all-webhook-targets-allowed-ports: '[{"protocol":"TCP","port":{{ .Values.global.webhookConfig.serverPort }}}]'
    {{- if and .Values.global.service.topologyAwareRouting.enabled (semverCompare "< 1.31-0" .Capabilities.KubeVersion.Version) }}
    {{- if semverCompare ">= 1.27-0" .Capabilities.KubeVersion.Version }}
    service.kubernetes.io/topology-mode: "auto"
    {{- else }}
    service.kubernetes.io/topology-aware-hints: "auto"
    {{- end }}
    {{- end }}
  labels:
{{ include "labels" . | indent 4 }}
    {{- if and .Values.global.service.topologyAwareRouting.enabled (semverCompare "< 1.32-0" .Capabilities.KubeVersion.Version) }}
    endpoint-slice-hints.resources.gardener.cloud/consider: "true"
    {{- end }}
spec:
  type: ClusterIP
  selector:
{{ include "labels" . | indent 4 }}
  ports:
  - port: 443
    protocol: TCP
    targetPort: {{ .Values.global.webhookConfig.serverPort }}
  {{- if and .Values.global.service.topologyAwareRouting.enabled (semverCompare ">= 1.31-0" .Capabilities.KubeVersion.Version) }}
  trafficDistribution: PreferClose
  {{- end }}
