apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dummy
  name: dummy
  namespace: { { .Release.Namespace } }
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dummy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
