---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-webhook
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      port: 9443
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}-webhook

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Chart.Name }}-webhook
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Chart.Name }}-tls
  dnsNames:
    - {{ .Chart.Name }}-webhook.{{ .Release.Namespace }}.svc
  issuerRef:
    name: selfsigned

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}

