apiVersion: v1
kind: Service
metadata:
  name: {{ template "gardener-extension.webhookName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    networking.resources.gardener.cloud/from-world-to-ports: '[{"protocol":"TCP","port": 9443}]'
  labels:
    {{- include "gardener-extension.webhookLabels" . | nindent 4 }}
spec:
  ports:
    - name: https
      port: 9443
      protocol: TCP
  selector:
    {{- include "gardener-extension.webhookSelectorLabels" . | nindent 4 }}