---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "gardener-extension-acl.webhookname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gardener-extension-acl.webhookLabels" . | nindent 4 }}
spec:
  ports:
    - name: https
      port: 9443
      protocol: TCP
  selector:
    {{- include "gardener-extension-acl.webhookSelectorLabels" . | nindent 4 }}