{{- if .Values.vpnEnvoyFilterSpec }}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: acl-vpn-{{ .Values.suffix }}
  namespace: {{ .Values.targetNamespace }}
  labels:
    {{- include "gardener-extension.labels" . | nindent 4 }}
spec: {{- .Values.vpnEnvoyFilterSpec | toYaml | nindent 2 }}
{{- end }}
